# Nome da pipeline
name: Run Basic Testes

# Em que momento será executada
on:
    pull_request:
        branches: [master]

        name: End-to-end tests
        on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
        record: true
        env: CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}


# O que vai ser feito nessa pipeline
# Só temos um job: rodar os testes
# jobs:
#     cypress-run:
#         # máquina que será executado
#         runs-on: ubuntu-latest
#         # Passo a passo para rodar os testes
#         steps:
#             # Clone do projeto
#         - name: Checkout do projeto/Clone do projeto
#           uses: actions/checkout@v3

#             # Exemplo de execução no terminal
#         - name: Instalar dependencias do projto
#           uses: npm install

#             # Execução e config do projeto
#             - name: Cypress run
#               uses: cypress-io/github-action@v6